### ISSUE TITLE
Could you please add a LICENSE to this github repo?

### ISSUE THREAD

**Issue by zhouyiheng11** [tansey/bb-fdr#1]
Hi Wesley, 

Thank you for sharing your implementation of BB-FDR. I am a scientist from Amazon and find your work very interesting. However, in order for me to use your code, it has to have a certain LICENSE (e.g. MIT LICENSE). I wonder if you could add a LICENSE to your repo so that I could use your code for development purpose? Thank you for your time.

Best,
Yiheng

**Comment by tansey** [comment]
Hi, thanks for the interest. I've added the MIT license.
